web-compile:
  sass:
    files:
      src/scss/syft-theme.scss: syft_theme/static/syft-theme.min.css
    precision: 5
    sourcemap: false
    format: compressed
  js:
    files:
      src/js/syft-theme.js: syft_theme/static/syft-theme.min.js
